fix: validation checks should always be run on each push to master

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,9 +1,7 @@
-name: Release
+name: Validate and Release
 
 on:
   push:
-    paths:
-      - VERSION # only trigger on changes to the VERSION file
     branches:
       - master
 
@@ -11,7 +9,28 @@ permissions:
   contents: write # grant permissions to create releases
 
 jobs:
+  validate:
+    name: Validate
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Install Nix
+        uses: cachix/install-nix-action@v31
+        with:
+          github_access_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Lint
+        run: nix develop .#dev --command bash -c 'make check'
+
+      - name: Test
+        run: nix develop --command secrets version
+
   release:
+    name: Release
+    needs: validate
+    if: contains(github.event.head_commit.modified, 'VERSION')
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout Repository
@@ -19,41 +38,26 @@ jobs:
 
       - name: Get Version
         id: get_version
-        run: VERSION="$(cat VERSION)" && echo "version=${VERSION}" >> $GITHUB_OUTPUT
+        run: VERSION="$(cat VERSION)" && echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
 
       - name: Check Release
         id: check_release
         run: |
-          VERSION="v${{ steps.get_version.outputs.version }}"
-          if [ -z "$(git tag -l "${VERSION}")" ]; then
-            echo "Tag ${VERSION} does not exist - continuing"
-            echo "skip=false" >> "${GITHUB_OUTPUT}"
+          TAG="v${{ steps.get_version.outputs.version }}"
+          if [ -z "$(git tag -l "${TAG}")" ]; then
+            echo "info: tag ${TAG} does not exist - proceeding with release ✅"
+            exit 0
           else
-            echo "Tag ${VERSION} already exists - skipping release"
-            echo "skip=true" >> "${GITHUB_OUTPUT}"
+            echo "error: tag ${TAG} already exists ❌"
+            exit 1
           fi
-
-      - name: Install Nix
-        uses: cachix/install-nix-action@v31
-        if: steps.check_release.outputs.skip == 'false'
-        with:
-          github_access_token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Lint
-        if: steps.check_release.outputs.skip == 'false'
-        run: nix develop .#dev --command bash -c 'make check'
-
-      - name: Test
-        if: steps.check_release.outputs.skip == 'false'
-        run: nix develop --command secrets version
 
       - name: Release
         uses: softprops/action-gh-release@v2
-        if: steps.check_release.outputs.skip == 'false'
         with:
           name: "Release v${{ steps.get_version.outputs.version }}"
           tag_name: "v${{ steps.get_version.outputs.version }}"
-          token: ${{ secrets.GITHUB_TOKEN }}
+          token: "${{ secrets.GITHUB_TOKEN }}"
           generate_release_notes: true
           make_latest: true
           prerelease: false
