chore: use nixos-unstable and refactor release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,13 +35,15 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
-          fetch-depth: 2
+          fetch-depth: 0
 
       - name: Check Version
         id: check_version
         run: |
+          set -euo pipefail
+
           echo "info: checking if VERSION file exists"
-          if [ ! -f "VERSION" ]; then
+          if [ ! -f VERSION ]; then
             echo "info: VERSION file does not exist - skipping release"
             echo "changed=false" >> "${GITHUB_OUTPUT}"
             exit 0
@@ -49,37 +51,36 @@ jobs:
             echo "info: VERSION file exists"
           fi
 
-          if [ "$(git rev-list --count HEAD)" -eq 1 ]; then
-            echo "info: first commit detected - proceeding with release"
+          echo "info: checking if any tags exist"
+          if [ "$(git tag | wc -l)" -eq 0 ]; then
+            echo "info: first release detected - proceeding"
             echo "changed=true" >> "${GITHUB_OUTPUT}"
             exit 0
           else
-            echo "info: checking if VERSION file was modified"
+            echo "info: tags exist"
           fi
 
-          if git diff --name-only HEAD^ HEAD | grep -q '^VERSION$'; then
-            echo "info: detected VERSION file change - proceeding with release"
-            echo "changed=true" >> "${GITHUB_OUTPUT}"
-          else
-            echo "info: VERSION file has not changed - skipping release"
+          echo "info: checking for new version"
+          CURR_VERSION="$(git describe --tags --abbrev=0 | sed 's/^v//')"
+          NEXT_VERSION="$(cat VERSION | sed 's/^v//')"
+          if [ "${NEXT_VERSION}" == "${CURR_VERSION}" ]; then
+            echo "info: version has not changed - skipping release"
             echo "changed=false" >> "${GITHUB_OUTPUT}"
-          fi
-
-      - name: Get Version
-        if: steps.check_version.outputs.changed == 'true'
-        id: get_version
-        run: VERSION="$(cat VERSION)" && echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
-
-      - name: Check Release
-        if: steps.check_version.outputs.changed == 'true'
-        id: check_release
-        run: |
-          TAG="v${{ steps.get_version.outputs.version }}"
-          if [ -z "$(git tag -l "${TAG}")" ]; then
-            echo "info: tag ${TAG} does not exist ✅"
             exit 0
           else
-            echo "error: tag ${TAG} already exists ❌"
+            echo "info: potentially new version detected"
+          fi
+
+          echo "info: checking if version ${NEXT_VERSION} already exists"
+          if [ -z "$(git tag -l "v${NEXT_VERSION}")" ]; then
+            echo "info: version ${NEXT_VERSION} is available ✅"
+            echo "version=${NEXT_VERSION}" >> "${GITHUB_OUTPUT}"
+            echo "changed=true" >> "${GITHUB_OUTPUT}"
+            exit 0
+          else
+            echo "error: version ${NEXT_VERSION} already exists ❌"
+            echo "version=${NEXT_VERSION}" >> "${GITHUB_OUTPUT}"
+            echo "changed=false" >> "${GITHUB_OUTPUT}"
             exit 1
           fi
 
@@ -87,8 +88,8 @@ jobs:
         if: steps.check_version.outputs.changed == 'true'
         uses: softprops/action-gh-release@v2
         with:
-          name: "Release v${{ steps.get_version.outputs.version }}"
-          tag_name: "v${{ steps.get_version.outputs.version }}"
+          name: "Release v${{ steps.check_version.outputs.version }}"
+          tag_name: "v${{ steps.check_version.outputs.version }}"
           token: "${{ secrets.GITHUB_TOKEN }}"
           generate_release_notes: true
           make_latest: true
